### ISSUE TITLE
[enhancement] navigate

### ISSUE THREAD

**Issue by witterlee** [idea2app/React-Router-class-tools#2]
https://stackoverflow.com/questions/71499678/navigate-using-react-router-dom-v6-after-performing-user-action

Adding navigate will make it more complete. redirect is also a common usage scenario

**Comment by TechQuery** [comment]
If you use Hash Router, `window.location.hash = '/your/route?key=value` is an easy way to navigate pages.

But full v5 compatibility of `this.props.history` is an unclear problem for now: https://github.com/idea2app/React-Router-class-tools/issues/1#issuecomment-1133926299
